# Generated by Django 6.0.4 on 2026-04-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('food_item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('total_price', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
